# =============================================================================
# SonarQube Configuration — auth-service
# Conformité DSI §2 : SonarQube Quality Gate A bloquant
# =============================================================================

sonar.projectKey=d2f_auth
sonar.projectName=d2f_auth
sonar.projectVersion=2026.01.01.0

# Sources
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Rapports de tests
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Encodage
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/target/**,**/*.class,**/db/migration/**
