# Application
spring.application.name=formation-service

  # Datasource

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/d2f}
spring.datasource.username=${DB_USER:app_user_formation}
spring.datasource.password=${DB_PASSWORD}

  # JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
  
  # File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
  
  # RabbitMQ AMQP
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:}

  # Rabbit Listener
spring.rabbitmq.listener.simple.acknowledge-mode=auto
  
  # Server
server.port=8088


  # Logging
logging.level.com.azure.identity=DEBUG
logging.level.com.microsoft.graph.authentication=DEBUG
logging.level.org.springframework.security=DEBUG