-- S-3: Add JPA audit trail columns to all formation service tables
ALTER TABLE formation.formations
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE formation.bureaux
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE departements
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE documents
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE enseignants
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE formation_competences
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE inscriptions
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE presences
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE seances
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE ups
    ADD COLUMN IF NOT EXISTS created_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMP,
    ADD COLUMN IF NOT EXISTS created_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS updated_by  VARCHAR(150),
    ADD COLUMN IF NOT EXISTS version     BIGINT DEFAULT 0 NOT NULL;
