sonar.projectKey=d2f_webapp
sonar.projectName=d2f_webapp
sonar.projectVersion=2026.03.14.2
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**/*,src/**/*.test.*,src/**/*.spec.*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=dist/**,node_modules/**,coverage/**,.scannerwork/**,src/setupTests.js,src/styles/assets/**
