from typing import Protocol

from app.domain.entities.alert import Alert
from app.domain.entities.competency import Competency
from app.domain.entities.recommendation import Recommendation
from app.domain.entities.risk_profile import RiskProfile
from app.domain.entities.skill_gap import SkillGap
from app.domain.entities.teacher import Teacher
from app.domain.entities.training_need import TrainingNeed
from app.domain.services.ranking_service import TrainingCandidate


class TeacherSource(Protocol):
    def get_teacher(self, teacher_id: str) -> Teacher | None: ...

    def resolve_user_teacher(self, user_id: str) -> Teacher | None: ...

    def list_teachers(self) -> list[Teacher]: ...


class CompetencySource(Protocol):
    def list_competencies(self) -> list[Competency]: ...

    def list_competencies_for_scope(
        self, up_id: str | None, dept_id: str | None, specialite: str | None
    ) -> list[Competency]: ...

    def get_teacher_savoir_levels(self, teacher_id: str) -> dict[int, int]: ...

    def get_teacher_savoir_levels_history(self, teacher_id: str) -> dict[int, list[tuple[str, int]]]: ...


class FormationSource(Protocol):
    def get_candidates_for_competency(self, competence_id: int) -> list[TrainingCandidate]: ...

    def get_completed_formation_ids(self, teacher_id: str) -> set[int]: ...

    def get_attendance_rate(self, teacher_id: str) -> float: ...

    def get_days_since_last_activity(self, teacher_id: str) -> float | None: ...


class EvaluationSource(Protocol):
    def get_avg_eval_score(self, teacher_id: str) -> float | None: ...


class BesoinSource(Protocol):
    def count_declared_needs(self, teacher_id: str, months: int) -> int: ...


class AnalysisRepository(Protocol):
    def save_skill_gaps(self, gaps: list[SkillGap], teacher_id: str | None = None) -> None: ...

    def list_gaps_by_teacher(self, teacher_id: str) -> list[SkillGap]: ...

    def save_risk_snapshot(self, profile: RiskProfile) -> None: ...

    def save_recommendations(self, recommendations: list[Recommendation]) -> None: ...


class ModelPort(Protocol):
    def predict_gaps(self, teacher_id: str) -> list[SkillGap] | None: ...

    def predict_risk(self, teacher_id: str) -> RiskProfile | None: ...

    def status(self) -> dict: ...


class AlertRepository(Protocol):
    def save(self, alert: Alert) -> Alert: ...

    def list_alerts(self, page: int, size: int, severity: str | None = None, status: str | None = None, target_type: str | None = None) -> tuple[list[Alert], int]: ...

    def list_for_teacher(self, teacher_id: str, page: int, size: int, severity: str | None = None, status: str | None = None) -> tuple[list[Alert], int]: ...

    def list_for_department(self, department_id: str, page: int, size: int, severity: str | None = None, status: str | None = None) -> tuple[list[Alert], int]: ...

    def list_open_since(self, cutoff_days: int) -> list[Alert]: ...

    def update_status(self, alert_id: int, status: str, actor: str | None = None, comment: str | None = None) -> Alert | None: ...


class TrainingNeedRepository(Protocol):
    def save(self, need: TrainingNeed) -> TrainingNeed: ...

    def list_needs(self, page: int, size: int, need_type: str | None = None, scope_type: str | None = None) -> tuple[list[TrainingNeed], int]: ...

    def list_for_teacher(self, teacher_id: str, page: int, size: int) -> tuple[list[TrainingNeed], int]: ...

    def list_for_department(self, department_id: str, page: int, size: int) -> tuple[list[TrainingNeed], int]: ...

    def close(self, need_id: int) -> TrainingNeed | None: ...


class DashboardRepository(Protocol):
    def save_snapshot(self, scope: str, scope_id: str | None, kpis: dict) -> None: ...

    def latest_snapshot(self, scope: str, scope_id: str | None = None) -> dict | None: ...

    def declining_trends(self, scope: str, scope_id: str | None = None) -> list[dict]: ...


class IdempotencyRepository(Protocol):
    def already_processed(self, event_id: str) -> bool: ...

    def mark_processed(self, event_id: str, event_type: str | None = None) -> None: ...
