kind: pipeline
type: docker
name: esprit-d2f-recommandation-formateur quality ci

trigger:
  branch:
  - release/*
  event:
  - push

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: build and publish
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    settings:
      build_args:
      - BUILD_ENV=qa
      - ENV_FILE=.env-qa
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      dockerfile: Dockerfile
      experimental: true
      repo: 192.168.0.128:5000/d2f.esprit.tn/recommandation-formateur
      registry: 192.168.0.128:5000
      insecure: true
      tags:
        - ${DRONE_COMMIT:0:7}-qa

  - name: compose deploy
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.3.11
      username: esprit
      password:
        from_secret: ssh-3.11_password
      port: 22
      command_timeout: 2m
      script:
        - cd /home/esprit/espritD2F
        - sed -E -i "s|d2f.esprit.tn/recommandation-formateur:[^ ]+|d2f.esprit.tn/recommandation-formateur:${DRONE_COMMIT:0:7}-qa|g" docker-compose.yml
        - docker compose up -d


  - name: success notification
    image: drillster/drone-email
    settings:
      from: Drone-CI QA <notification-ops-qa@esprit.tn>
      host: smtp.office365.com
      port: 587
      username:
        from_secret: email_username_outlook
      password:
        from_secret: email_password_outlook
      recipients_only: true
      recipients:
        - seddik.bouzayani@esprit.tn
      subject: SUCCESS - ${DRONE_STAGE_NAME} pipeline [${DRONE_COMMIT:0:7}-qa]
      body: |
        The Pipeline ${DRONE_STAGE_NAME} has completed successfully.
        <br>
        Git Commit : ${DRONE_COMMIT:0:7}-qa | Git Event : ${DRONE_BUILD_EVENT}
        <br>
        Git Branch : ${DRONE_BRANCH} | Git REF : ${DRONE_COMMIT_REF}
        <br>
        Git Branch Source : ${DRONE_SOURCE_BRANCH} | Git Branch Target : ${DRONE_TARGET_BRANCH}
        <br>
        Git Author : ${DRONE_COMMIT_AUTHOR}
        <br>
        Link: ${DRONE_BUILD_LINK}
    when:
      status:
        - success

  - name: failure notification
    image: drillster/drone-email
    settings:
      from: Drone-CI QA <notification-ops-qa@esprit.tn>
      host: smtp.office365.com
      port: 587
      username:
        from_secret: email_username_outlook
      password:
        from_secret: email_password_outlook
      recipients_only: true
      recipients:
        - seddik.bouzayani@esprit.tn
      subject: FAILURE ${DRONE_STAGE_NAME} pipeline [${DRONE_COMMIT:0:7}-qa]
      body: |
        The Pipeline ${DRONE_STAGE_NAME} has failed.
        <br>
        Git Commit : ${DRONE_COMMIT:0:7}-qa | Git Event : ${DRONE_BUILD_EVENT}
        <br>
        Git Branch : ${DRONE_BRANCH} | Git REF : ${DRONE_COMMIT_REF}
        <br>
        Git Branch Source : ${DRONE_SOURCE_BRANCH} | Git Branch Target : ${DRONE_TARGET_BRANCH}
        <br>
        Git Author : ${DRONE_COMMIT_AUTHOR}
        <br>
        Link: ${DRONE_BUILD_Link}
    when:
      status:
        - failure