server.port=8089
spring.application.name=service-analyse

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# URLs des microservices (pour développement local)
services.evaluation.url=http://localhost:8087
services.formation.url=http://localhost:8088
services.competence.url=http://localhost:8005
services.besoin-formation.url=http://localhost:8004
