server.port=8089
server.error.include-stacktrace=never

# URLs des microservices (overridables via env vars)
services.evaluation.url=${SERVICES_EVALUATION_URL:http://evaluation-service:8087}
services.formation.url=${SERVICES_FORMATION_URL:http://formation-service:8082}
services.competence.url=${SERVICES_COMPETENCE_URL:http://competence-service:8005}
services.besoin-formation.url=${SERVICES_BESOIN_FORMATION_URL:http://besoin-formation-service:8004}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always