# SPRING
spring.main.allow-bean-definition-overriding=true
spring.application.name=besoinsformation-service

# DATASOURCE

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/d2f}
spring.datasource.username=${DB_USER:app_user_besoinsformation}
spring.datasource.password=${DB_PASSWORD}


# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# RabbitMQ (AMQP)
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:}

# Rabbit Listener
spring.rabbitmq.listener.simple.acknowledge-mode=auto

# SERVER
server.port=8004


# JWT
# IMPORTANT : définir JWT_SECRET comme variable d'environnement (min 64 chars, HS512)
jwt.secret=${JWT_SECRET}

# LOGGING
logging.level.org.springframework.security=DEBUG
